### ISSUE TITLE
New Logo offer - OpenHospital

### ISSUE THREAD

**Issue by naufaldsg** [naufaldsg/naufal.id#1]
Hi, @marcoM32. Sorry for mention you here. I just want to offer new logo for your website https://www.open-hospital.org/ based on your repo [marcoM32/OpenHospital](https://github.com/marcoM32/OpenHospital)

I have seen the current logo, and I think that is to generic and there is no message there. If you allowed, I can make it for you, like [SeaMapDroid](https://github.com/marcoM32/SeaMapDroid) logo :)

![openhospital](https://www.open-hospital.org/wp-content/uploads/2017/03/logo_OH_small.png)

**Comment by marcoM32** [comment]
Hi @naufaldsg, the project OpenHospital is a official software development by Informatici senza frontiere. All of contributions needs to be done on the official repository [here](https://github.com/informatici/OpenHospital). (My repo is only a fork of it)

Please refer directly to Informatici senza frontiere for your idea.

**Comment by naufaldsg** [comment]
Ahh I see. Thank you
